#! /bin/sh

# 随机公平队列


# 下载限制

# 清空根队列
tc qdisc del dev br-lan root >/dev/null 2>&1

# 加一个根队列
tc qdisc add dev br-lan root handle 1: sfq quantum 1514b perturb 15


# 上传限制

# 清空根队列
tc qdisc del dev eth0.2 root >/dev/null 2>&1

# 加一个根队列
tc qdisc add dev eth0.2 root handle 1: sfq quantum 1514b perturb 15
